name: Build

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$PWD:$PWD/spotify_lyric" >> $GITHUB_ENV
      - name: Run test
        working-directory: tests
        run: python -m unittest discover . "*_test.py"
      - name: Build .app
        run: pyinstaller SpotifyLyrics.pyw -F -w -i icon.icns --add-data "icon.png:."
      - name: Upload .app
        uses: actions/upload-artifact@v2.1.4
        with:
          name: macos
          path: dist/SpotifyLyrics.app
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dbus
        run: sudo apt install libdbus-1-dev libdbus-glib-1-dev --yes
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$PWD:$PWD/spotify_lyric" >> $GITHUB_ENV
      - name: Run test
        working-directory: tests
        run: python -m unittest discover . "*_test.py"
      - name: Build executable
        run: pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png:."
      - name: Upload executable
        uses: actions/upload-artifact@v2.1.4
        with:
          name: linux
          path: dist/SpotifyLyrics
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=${env:PYTHONPATH};${env:GITHUB_WORKSPACE};${env:GITHUB_WORKSPACE}/spotify_lyric" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Run test
        working-directory: tests
        run: python -m unittest discover . "*_test.py"
      - name: Build .exe
        run: pyinstaller SpotifyLyrics.py -F -i icon.ico --add-data "icon.png;."
      - name: Upload .exe
        uses: actions/upload-artifact@v2.1.4
        with:
          name: windows
          path: dist/SpotifyLyrics.exe
